### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AntiWarforever** [Doc-SLAV/boolfamily#2]
when i use user id get this error
Activating virtual environment...
Starting the bot...
2024-10-10 07:29:29,047 - ERROR - An unexpected error occurred: 'query_id'
i think don't work on user_id , just work on query_id
![image](https://github.com/user-attachments/assets/eae1fab0-3925-4348-9e95-f10305b0a9ba)
my user_id >
user=%7B%22id%22%3A721875952%2C%22first_name%22%3A%225on%206%F0%9F%90%B0%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22k5lg5ll%22%2C%22language_code%22%3A%22en%22%2C%22allows_write_to_pm%22%3Atrue%7D&chat_instance=911444444979747109&chat_type=sender&start_param=977Z&auth_date=1728533848&hash=5b0e7026a6dc941040565643d71a6a5f5b555a8956ffff714f4d9025ec509f9

**Comment by Doc-SLAV** [comment]
yeah, just work for query_id
thanks for info
